services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3020:3000"
    networks:
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=http://langfuse-server:3020
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    networks:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis
    volumes:
      - redisdata:/data

  flowise:
    image: michameiu/flowise:v1.0.0.arm

    networks:
      - redis
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - 3010:3000

    volumes:
      - myapp:/myapp/
      - flowise:/root/.flowise/
  
volumes:
  myapp:
  redisdata:
  database_data:
  flowise:

networks:
  redis:

